### PR TITLE
Cleanup of autovector interrupt code

### PR DESCRIPTION
**Pull request by StefanBruens**

### CODE REVIEW

**Comment by djmuhlestein** [comment]
It's been quite a while since I worked on the code for interrupts jump/tables etc.  I'm hesitant to pull this change as the current source is working quite stable.  I'm not sure what is wrong without digging into it further that is fixed by this change.  Can you elaborate a bit?

Thanks
Dennis

**Comment by StefanBruens** [comment]
The current definition creates 352 bytes of dead code (8 byte per ISR). From a functional standpoint,
both are equivalent. After linking, both versions contain a ljmp to the jump table (e.g. 0x3f00) in the interupt table for interupt 8 (USB)/10 (GPIF), i.e. at address 0x43 resp. 0x53.

ASM dump from the modified source:
```asm
                                    814 ;--------------------------------------------------------
                                    815 ; interrupt vector 
                                    816 ;--------------------------------------------------------
                                    817         .area HOME    (CODE)
      000000                        818 __interrupt_vect:
      000000 02r00r00         [24]  819         ljmp    __sdcc_gsinit_startup
      000003 32               [24]  820         reti
      000004                        821         .ds     7
      00000B 32               [24]  822         reti
      00000C                        823         .ds     7
      000013 32               [24]  824         reti
      000014                        825         .ds     7
      00001B 32               [24]  826         reti
      00001C                        827         .ds     7
      000023 32               [24]  828         reti
      000024                        829         .ds     7
      00002B 32               [24]  830         reti
      00002C                        831         .ds     7
      000033 32               [24]  832         reti
      000034                        833         .ds     7
      00003B 32               [24]  834         reti
      00003C                        835         .ds     7
      000043 02r00r00         [24]  836         ljmp    _usb_isr
      000046                        837         .ds     5
      00004B 32               [24]  838         reti
      00004C                        839         .ds     7
      000053 02r00r00         [24]  840         ljmp    _gpif_isr
                                    841 ;--------------------------------------------------------
                                    842 ; global & static initialisations
                                    843 ;--------------------------------------------------------
                                    844         .area HOME    (CODE)
                                    845         .area GSINIT  (CODE)
                                    846         .area GSFINAL (CODE)
                                    847         .area GSINIT  (CODE)
                                    848         .globl __sdcc_gsinit_startup
                                    849         .globl __sdcc_program_startup
                                    850         .globl __start__stack
                                    851         .globl __mcs51_genXINIT
                                    852         .globl __mcs51_genXRAMCLEAR
                                    853         .globl __mcs51_genRAMCLEAR
                                    854         .area GSFINAL (CODE)
      000000 02r00r56         [24]  855         ljmp    __sdcc_program_startup
                                    856 ;--------------------------------------------------------
                                    857 ; Home
                                    858 ;--------------------------------------------------------
                                    859         .area HOME    (CODE)
                                    860         .area HOME    (CODE)
      000056                        861 __sdcc_program_startup:
      000056 02r01r32         [24]  862         ljmp    _main
```
compare this with the ASM dump from the unmodified source:
```asm
                                   815 ;--------------------------------------------------------
                                    816 ; interrupt vector 
                                    817 ;--------------------------------------------------------
                                    818         .area HOME    (CODE)
      000000                        819 __interrupt_vect:
      000000 02r00r00         [24]  820         ljmp    __sdcc_gsinit_startup
      000003 32               [24]  821         reti
      000004                        822         .ds     7
      00000B 32               [24]  823         reti
      00000C                        824         .ds     7
      000013 32               [24]  825         reti
      000014                        826         .ds     7
      00001B 32               [24]  827         reti
      00001C                        828         .ds     7
      000023 32               [24]  829         reti
      000024                        830         .ds     7
      00002B 32               [24]  831         reti
      00002C                        832         .ds     7
      000033 32               [24]  833         reti
      000034                        834         .ds     7
      00003B 32               [24]  835         reti
      00003C                        836         .ds     7
      000043 32               [24]  837         reti
      000044                        838         .ds     7
      00004B 32               [24]  839         reti
      00004C                        840         .ds     7
      000053 32               [24]  841         reti
      000054                        842         .ds     7
      00005B 32               [24]  843         reti
      00005C                        844         .ds     7
      000063 32               [24]  845         reti
      000064                        846         .ds     7
      00006B 02r02r02         [24]  847         ljmp    _sudav_isr
      00006E                        848         .ds     5
      000073 02r02r29         [24]  849         ljmp    _sof_isr
      000076                        850         .ds     5
      00007B 02r00r00         [24]  851         ljmp    _sutok_isr
      00007E                        852         .ds     5
      000083 02r00r00         [24]  853         ljmp    _suspend_isr
      000086                        854         .ds     5
      00008B 02r02r4A         [24]  855         ljmp    _usbreset_isr
      00008E                        856         .ds     5
      000093 02r02r99         [24]  857         ljmp    _hispeed_isr
      000096                        858         .ds     5
      00009B 02r00r00         [24]  859         ljmp    _ep0ack_isr
      00009E                        860         .ds     5
      0000A3 02r00r00         [24]  861         ljmp    _ep0in_isr
      0000A6                        862         .ds     5
      0000AB 02r00r00         [24]  863         ljmp    _ep0out_isr
      0000AE                        864         .ds     5
      0000B3 02r00r00         [24]  865         ljmp    _ep1in_isr
      0000B6                        866         .ds     5
      0000BB 02r00r00         [24]  867         ljmp    _ep1out_isr
      0000BE                        868         .ds     5
      0000C3 02r00r00         [24]  869         ljmp    _ep2_isr
      0000C6                        870         .ds     5
      0000CB 02r00r00         [24]  871         ljmp    _ep4_isr
      0000CE                        872         .ds     5
      0000D3 02r00r00         [24]  873         ljmp    _ep6_isr
      0000D6                        874         .ds     5
      0000DB 02r00r00         [24]  875         ljmp    _ep8_isr
      0000DE                        876         .ds     5
      0000E3 02r00r00         [24]  877         ljmp    _ibn_isr
      0000E6                        878         .ds     5
      0000EB 02r00r00         [24]  879         ljmp    _ep0ping_isr
      0000EE                        880         .ds     5
      0000F3 02r00r00         [24]  881         ljmp    _ep1ping_isr
      0000F6                        882         .ds     5
      0000FB 02r00r00         [24]  883         ljmp    _ep2ping_isr
      0000FE                        884         .ds     5
      000103 02r00r00         [24]  885         ljmp    _ep4ping_isr
      000106                        886         .ds     5
      00010B 02r00r00         [24]  887         ljmp    _ep6ping_isr
      00010E                        888         .ds     5
      000113 02r00r00         [24]  889         ljmp    _ep8ping_isr
      000116                        890         .ds     5
      00011B 02r00r00         [24]  891         ljmp    _errlimit_isr
      00011E                        892         .ds     5
      000123 02r00r00         [24]  893         ljmp    _ep2isoerr_isr
      000126                        894         .ds     5
      00012B 02r00r00         [24]  895         ljmp    _ep4isoerr_isr
      00012E                        896         .ds     5
      000133 02r00r00         [24]  897         ljmp    _ep6isoerr_isr
      000136                        898         .ds     5
      00013B 02r00r00         [24]  899         ljmp    _ep8isoerr_isr
      00013E                        900         .ds     5
      000143 02r00r00         [24]  901         ljmp    _spare_isr
      000146                        902         .ds     5
      00014B 02r00r00         [24]  903         ljmp    _ep2pf_isr
      00014E                        904         .ds     5
      000153 02r00r00         [24]  905         ljmp    _ep4pf_isr
      000156                        906         .ds     5
      00015B 02r00r00         [24]  907         ljmp    _ep6pf_isr
      00015E                        908         .ds     5
      000163 02r00r00         [24]  909         ljmp    _ep8pf_isr
      000166                        910         .ds     5
      00016B 02r00r00         [24]  911         ljmp    _ep2ef_isr
      00016E                        912         .ds     5
      000173 02r00r00         [24]  913         ljmp    _ep4ef_isr
      000176                        914         .ds     5
      00017B 02r00r00         [24]  915         ljmp    _ep6ef_isr
      00017E                        916         .ds     5
      000183 02r00r00         [24]  917         ljmp    _ep8ef_isr
      000186                        918         .ds     5
      00018B 02r00r00         [24]  919         ljmp    _ep2ff_isr
      00018E                        920         .ds     5
      000193 02r00r00         [24]  921         ljmp    _ep4ff_isr
      000196                        922         .ds     5
      00019B 02r00r00         [24]  923         ljmp    _ep6ff_isr
      00019E                        924         .ds     5
      0001A3 02r00r00         [24]  925         ljmp    _ep8ff_isr
      0001A6                        926         .ds     5
      0001AB 02r00r00         [24]  927         ljmp    _gpifdone_isr
      0001AE                        928         .ds     5
      0001B3 02r00r00         [24]  929         ljmp    _gpifwf_isr
                                    930 ;--------------------------------------------------------
                                    931 ; global & static initialisations
                                    932 ;--------------------------------------------------------
                                    933         .area HOME    (CODE)
                                    934         .area GSINIT  (CODE)
                                    935         .area GSFINAL (CODE)
                                    936         .area GSINIT  (CODE)
                                    937         .globl __sdcc_gsinit_startup
                                    938         .globl __sdcc_program_startup
                                    939         .globl __start__stack
                                    940         .globl __mcs51_genXINIT
                                    941         .globl __mcs51_genXRAMCLEAR
                                    942         .globl __mcs51_genRAMCLEAR
                                    943         .area GSFINAL (CODE)
      000000 02r01rB6         [24]  944         ljmp    __sdcc_program_startup
                                    945 ;--------------------------------------------------------
                                    946 ; Home
                                    947 ;--------------------------------------------------------
                                    948         .area HOME    (CODE)
                                    949         .area HOME    (CODE)
      0001B6                        950 __sdcc_program_startup:
      0001B6 02r01r34         [24]  951         ljmp    _main
----

**Comment by djmuhlestein** [comment]
I think I recall having issues creating new interrupts in your derived firmware easily.  The idea was to be able to simply implement the interrupt handler and have it work.  That might be why it was the way it was.  Does it still work that way?

**Comment by StefanBruens** [comment]
Everything works the same as before - you declare interrupt handlers like before, for normal and autovector interrupts.

I have tested it with the la16fw firmware, and it works.

**Comment by djmuhlestein** [comment]
Sounds good to me.  I'll play around with it when I come back to it sooner or later.  I still have a couple firmware projects using fx2lib.

**Pull request merged**
