### PR TITLE
Adding the needed libusb-1.0-dev package to travis build.

### PR DESCRIPTION
**Pull request by mithro**

### CODE REVIEW

**Comment by mithro** [comment]
BTW You'll want to enable the travis repo hooks.

**Comment by mithro** [comment]
Friendly ping....

**Comment by djmuhlestein** [comment]
honestly I haven't had a chance to look into the travis repo thing at all.
I haven't got any idea what it's useful for or  how it works.

**Comment by mithro** [comment]
The idea is that when enabled it will check that everything still compiles and give you a green box in a pull request if it still works. Sadly it can't check that things still work, but compiling is a good first step :)

**Comment by djmuhlestein** [comment]
Where is the repo set up that compiles?  Who enables the hooks I mean?

**Comment by mithro** [comment]
You log into https://travis-ci.org and enable the repository (which should set up a hook for you at https://github.com/djmuhlestein/fx2lib/settings/hooks). Then it should all be automagical from then.

**Comment by mithro** [comment]
Did you figure out how to enable the travis hooks?

**Comment by djmuhlestein** [comment]
I looked at the site but I'm not too worried about logging in and enabling
them right now.  I'm using fx2lib in maintenance mode only since I'm
focusing all active development on the fx3 chip.  fx2 still has some good
niche usages though, if I have a project that comes back to it I'll switch
back to actively maintaining it.

**Comment by mithro** [comment]
Would you mind if I "took over" development of the library then? It is
likely for the next 6 month's I'll have more things to contribute here.

>

**Comment by djmuhlestein** [comment]
Since it's open source you're always free to fork and do with the
repository as you wish.  For this specific repository though I still work
for the company that I originally developed it with.  Although we aren't
actively developing it right now we do still support products with the fx2
chip so I'm not quite ready to call it abandoned :)

**Pull request merged**
